export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  dateSort: number;
  readTime: string;
  cover: string;
  href: string;
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "eloralintide-vs-retatrutide-efficacy-and-tolerance",
    title: "Eloralintide vs Retatrutide: Efficacy and Tolerance",
    excerpt: "Eloralintide presents a high-potency amylin-agonist pathway requiring precise management of dose-dependent pharmacokinetics compared to retatrutide.",
    category: "Protocols",
    date: "Aug 30, 2026",
    dateSort: 20260830,
    readTime: "3 min read",
    cover: "/blog/eloralintide-vs-retatrutide-efficacy-and-tolerance/cover",
    href: "/blog/eloralintide-vs-retatrutide-efficacy-and-tolerance",
  },
  {
    slug: "vip-peptide-nasal-spray-efficacy-and-pharmacokinetics",
    title: "VIP Peptide Nasal Spray: Efficacy and Pharmacokinetics",
    excerpt: "Vasoactive Intestinal Peptide shows anti-inflammatory potential in animal models, but its extremely poor metabolic stability limits intranasal clinical utility.",
    category: "Science",
    date: "Aug 29, 2026",
    dateSort: 20260829,
    readTime: "3 min read",
    cover: "/blog/vip-peptide-nasal-spray-efficacy-and-pharmacokinetics/cover",
    href: "/blog/vip-peptide-nasal-spray-efficacy-and-pharmacokinetics",
  },
  {
    slug: "thymosin-alpha-1-benefits-vs-tb-500-immune-response",
    title: "Thymosin Alpha-1 Benefits vs TB-500: Immune Response",
    excerpt: "Thymosin alpha-1 benefits stem from T-cell modulation for viral response, whereas TB-500 targets tissue repair. Discover their specific mechanisms and markers.",
    category: "Science",
    date: "Aug 26, 2026",
    dateSort: 20260826,
    readTime: "3 min read",
    cover: "/blog/thymosin-alpha-1-benefits-vs-tb-500-immune-response/cover",
    href: "/blog/thymosin-alpha-1-benefits-vs-tb-500-immune-response",
  },
  {
    slug: "is-retatrutide-the-same-as-ozempic-clinical-trial-outcomes",
    title: "Is Retatrutide the Same as Ozempic? Clinical Trial Outcomes",
    excerpt: "Retatrutide is an investigational triple-agonist, while Ozempic is an FDA-approved single-agonist. Clinical trials reveal distinct outcomes and safety risks.",
    category: "Biomarkers",
    date: "Aug 24, 2026",
    dateSort: 20260824,
    readTime: "5 min read",
    cover: "/blog/is-retatrutide-the-same-as-ozempic-clinical-trial-outcomes/cover",
    href: "/blog/is-retatrutide-the-same-as-ozempic-clinical-trial-outcomes",
  },
  {
    slug: "orforglipron-para-que-sirve-oral-pharmacokinetics",
    title: "Orforglipron Para Que Sirve: Oral Pharmacokinetics",
    excerpt: "Orforglipron is a daily oral small-molecule GLP-1 agonist under investigation for obesity and type 2 diabetes, bypassing strict fasting absorption protocols.",
    category: "Science",
    date: "Aug 23, 2026",
    dateSort: 20260823,
    readTime: "4 min read",
    cover: "/blog/orforglipron-para-que-sirve-oral-pharmacokinetics/cover",
    href: "/blog/orforglipron-para-que-sirve-oral-pharmacokinetics",
  },
  {
    slug: "glp-1-receptor-agonists-metabolic-superiority-of-cagrisema",
    title: "GLP-1 Receptor Agonists: Metabolic Superiority of CagriSema",
    excerpt: "Dual-agonists represent the next evolution in metabolic therapy. By combining semaglutide with cagrilintide, CagriSema targets synergistic satiety signaling.",
    category: "Protocols",
    date: "Aug 21, 2026",
    dateSort: 20260821,
    readTime: "4 min read",
    cover: "/blog/glp-1-receptor-agonists-metabolic-superiority-of-cagrisema/cover",
    href: "/blog/glp-1-receptor-agonists-metabolic-superiority-of-cagrisema",
  },
  {
    slug: "bpc-157-apeiron-clinical-evidence-and-mechanism",
    title: "BPC-157 Apeiron: Clinical Evidence and Mechanism",
    excerpt: "BPC-157 works by modulating biological signaling pathways. Rodent data shows robust tissue repair, but human randomized clinical trials do not exist.",
    category: "Science",
    date: "Aug 20, 2026",
    dateSort: 20260820,
    readTime: "3 min read",
    cover: "/blog/bpc-157-apeiron-clinical-evidence-and-mechanism/cover",
    href: "/blog/bpc-157-apeiron-clinical-evidence-and-mechanism",
  },
  {
    slug: "retatrutide-pronunciation-mechanism-and-trial-data",
    title: "Retatrutide Pronunciation, Mechanism, and Trial Data",
    excerpt: "Pronounced reh-tuh-TROO-tide, this experimental triple-hormone-receptor agonist targets GLP-1, GIP, and glucagon to reduce body weight and mobilize liver fat.",
    category: "Science",
    date: "Aug 19, 2026",
    dateSort: 20260819,
    readTime: "4 min read",
    cover: "/blog/retatrutide-pronunciation-mechanism-and-trial-data/cover",
    href: "/blog/retatrutide-pronunciation-mechanism-and-trial-data",
  },
  {
    slug: "cjc-1295ipamorelin-before-and-after-in-women-biomarkers",
    title: "CJC-1295/Ipamorelin Before and After in Women: Biomarkers",
    excerpt: "CJC-1295 and Ipamorelin function as a synergistic growth hormone secretagogue stack. Measuring efficacy requires tracking the specific delta in IGF-1.",
    category: "Science",
    date: "Aug 17, 2026",
    dateSort: 20260817,
    readTime: "3 min read",
    cover: "/blog/cjc-1295ipamorelin-before-and-after-in-women-biomarkers/cover",
    href: "/blog/cjc-1295ipamorelin-before-and-after-in-women-biomarkers",
  },
  {
    slug: "klow-80-peptide-blend-tracking-inflammation-and-repair",
    title: "KLOW 80 Peptide Blend: Tracking Inflammation and Repair",
    excerpt: "The KLOW 80 stack combines investigational peptides like KPV and BPC-157.",
    category: "Science",
    date: "Aug 16, 2026",
    dateSort: 20260816,
    readTime: "3 min read",
    cover: "/blog/klow-80-peptide-blend-tracking-inflammation-and-repair/cover",
    href: "/blog/klow-80-peptide-blend-tracking-inflammation-and-repair",
  },
  {
    slug: "klow-peptide-dosage-targeting-hpept1-expression-not-math",
    title: "KLOW Peptide Dosage: Targeting hPepT1 Expression, Not Math",
    excerpt: "KLOW peptide dosage strictly relies on the hPepT1 transporter for KPV uptake. In murine models, KPV uptake reduces intestinal inflammation.",
    category: "Science",
    date: "Aug 15, 2026",
    dateSort: 20260815,
    readTime: "4 min read",
    cover: "/blog/klow-peptide-dosage-targeting-hpept1-expression-not-math/cover",
    href: "/blog/klow-peptide-dosage-targeting-hpept1-expression-not-math",
  },
  {
    slug: "peach-and-lily-copper-peptide-the-cellular-remodeling-evidence",
    title: "Peach and Lily Copper Peptide: The Cellular Remodeling",
    excerpt: "GHK-Cu operates as a targeted biochemical signal for skin fibroblasts, initiating collagen synthesis and basal stem cell stabilization for structural tissue\u2026",
    category: "Science",
    date: "Aug 12, 2026",
    dateSort: 20260812,
    readTime: "4 min read",
    cover: "/blog/peach-and-lily-copper-peptide-the-cellular-remodeling-evidence/cover",
    href: "/blog/peach-and-lily-copper-peptide-the-cellular-remodeling-evidence",
  },
  {
    slug: "allies-of-skin-copper-tripeptide-explained-ghk-signals",
    title: "Allies of Skin Copper Tripeptide Explained: GHK Signals",
    excerpt: "The GHK tripeptide functions as a fundamental tissue remodeling signal that initiates cellular chemoattraction and modulates local inflammatory processes.",
    category: "Science",
    date: "Aug 11, 2026",
    dateSort: 20260811,
    readTime: "3 min read",
    cover: "/blog/allies-of-skin-copper-tripeptide-explained-ghk-signals/cover",
    href: "/blog/allies-of-skin-copper-tripeptide-explained-ghk-signals",
  },
  {
    slug: "mounjaro-long-term-use-icd-10-clinical-maintenance-data",
    title: "Mounjaro Long Term Use ICD 10: Clinical Maintenance Data",
    excerpt: "ICD-10 code Z79.85 designates the long-term use of medications like Mounjaro.",
    category: "Protocols",
    date: "Aug 10, 2026",
    dateSort: 20260810,
    readTime: "4 min read",
    cover: "/blog/mounjaro-long-term-use-icd-10-clinical-maintenance-data/cover",
    href: "/blog/mounjaro-long-term-use-icd-10-clinical-maintenance-data",
  },
  {
    slug: "supplements-to-take-with-wegovy-correlating-biomarkers",
    title: "Supplements to Take with Wegovy: Correlating Biomarkers",
    excerpt: "Semaglutide alters metabolic rates and body composition, requiring targeted nutritional interventions based on clinical trial data and specific blood panels.",
    category: "Protocols",
    date: "Aug 10, 2026",
    dateSort: 20260810,
    readTime: "3 min read",
    cover: "/blog/supplements-to-take-with-wegovy-correlating-biomarkers/cover",
    href: "/blog/supplements-to-take-with-wegovy-correlating-biomarkers",
  },
  {
    slug: "cjc-1295ipamorelin",
    title: "CJC-1295/Ipamorelin: The First Selective GH Secretagogue",
    excerpt: "Ipamorelin is a pentapeptide engineered to stimulate growth hormone release without off-target receptor activation. We detail its clinical pharmacology.",
    category: "Science",
    date: "Aug 8, 2026",
    dateSort: 20260808,
    readTime: "4 min read",
    cover: "/blog/cjc-1295ipamorelin/cover",
    href: "/blog/cjc-1295ipamorelin",
  },
  {
    slug: "cjc-1295",
    title: "CJC 1295: Pharmacokinetics and Growth Hormone Effects",
    excerpt: "Clinical data indicates CJC-1295 creates sustained elevations in IGF-1. Analyzing its true pharmacological effect requires multi-week biomarker tracking.",
    category: "Science",
    date: "Aug 7, 2026",
    dateSort: 20260807,
    readTime: "4 min read",
    cover: "/blog/cjc-1295/cover",
    href: "/blog/cjc-1295",
  },
  {
    slug: "tb-500",
    title: "TB-500 in Doping Tests: Detection and Biomarkers",
    excerpt: "TB-500 is a synthetic peptide flagged in equine doping tests via liquid chromatography-mass spectrometry, detected through its unique acetylated N-terminus.",
    category: "Science",
    date: "Aug 5, 2026",
    dateSort: 20260805,
    readTime: "4 min read",
    cover: "/blog/tb-500/cover",
    href: "/blog/tb-500",
  },
  {
    slug: "tirzepatide-clinical-trial",
    title: "Tirzepatide clinical trial results in Chinese adults",
    excerpt: "The SURMOUNT-CN trial demonstrates tirzepatide's efficacy for weight reduction in Chinese adults, highlighting the need to track specific metabolic biomarkers.",
    category: "Protocols",
    date: "Aug 2, 2026",
    dateSort: 20260802,
    readTime: "5 min read",
    cover: "/blog/tirzepatide-clinical-trial/cover",
    href: "/blog/tirzepatide-clinical-trial",
  },
  {
    slug: "select-trial",
    title: "SELECT trial: semaglutide and kidney outcomes",
    excerpt: "The SELECT trial demonstrates that once-weekly semaglutide 2.4 mg reduces major adverse cardiovascular events by 20% and impacts composite kidney endpoints.",
    category: "Protocols",
    date: "Aug 1, 2026",
    dateSort: 20260801,
    readTime: "3 min read",
    cover: "/blog/select-trial/cover",
    href: "/blog/select-trial",
  },
  {
    slug: "bpc-157-peptides",
    title: "BPC 157 Peptides: Mechanisms of Gastrointestinal Mucosal",
    excerpt: "BPC 157 peptides function as cytoprotective agents being researched for their capacity to maintain gastrointestinal structural stability and mucosal integrity.",
    category: "Science",
    date: "Jul 31, 2026",
    dateSort: 20260731,
    readTime: "3 min read",
    cover: "/blog/bpc-157-peptides/cover",
    href: "/blog/bpc-157-peptides",
  },
  {
    slug: "mitochondria-l",
    title: "Mitochondrial Signaling: Humanin and Metabolic Health",
    excerpt: "Humanin is a mitochondrial-derived peptide that regulates apoptosis and metabolic health. Research indicates it actively decreases circulating IGF-I levels.",
    category: "Science",
    date: "Jul 28, 2026",
    dateSort: 20260728,
    readTime: "4 min read",
    cover: "/blog/mitochondria-l/cover",
    href: "/blog/mitochondria-l",
  },
  {
    slug: "pharmacological-nuances-of-gnrh-analogs",
    title: "Pharmacological Nuances of GnRH Analogs: Pulsatility Limits",
    excerpt: "An educational analysis of the pharmacological nuances of GnRH analogs, exploring how exact pulsatility thresholds dictate receptor desensitization.",
    category: "Science",
    date: "Jul 24, 2026",
    dateSort: 20260724,
    readTime: "3 min read",
    cover: "/blog/pharmacological-nuances-of-gnrh-analogs/cover",
    href: "/blog/pharmacological-nuances-of-gnrh-analogs",
  },
  {
    slug: "clinical-evidence-reality-check-bpc-157-and-ghk-cu",
    title: "Clinical Evidence Reality Check: BPC-157 and GHK-Cu",
    excerpt: "Evaluating the clinical evidence reality check for BPC-157 and GHK-Cu reveals a stark absence of verified human trials despite decades of animal research.",
    category: "Science",
    date: "Jul 23, 2026",
    dateSort: 20260723,
    readTime: "2 min read",
    cover: "/blog/clinical-evidence-reality-check-bpc-157-and-ghk-cu/cover",
    href: "/blog/clinical-evidence-reality-check-bpc-157-and-ghk-cu",
  },
  {
    slug: "epithalon-and-telomerase-activation-risks",
    title: "Epithalon and Telomerase Activation Risks: Biomarkers",
    excerpt: "Evaluating epithalon and telomerase activation risks requires prioritizing baseline cancer-antigen panels and inflammatory tracking over theoretical longevity.",
    category: "Science",
    date: "Jul 22, 2026",
    dateSort: 20260722,
    readTime: "3 min read",
    cover: "/blog/epithalon-and-telomerase-activation-risks/cover",
    href: "/blog/epithalon-and-telomerase-activation-risks",
  },
  {
    slug: "aod-9604-and-the-reality-of-commercial-weight-loss-claims",
    title: "AOD-9604 and the Reality of Commercial Weight-Loss Claims",
    excerpt: "AOD-9604 is not FDA-approved for weight loss. The peptide lacks demonstrated clinical outcomes, emphasizing the need to track actual metabolic biomarkers.",
    category: "Science",
    date: "Jul 21, 2026",
    dateSort: 20260721,
    readTime: "3 min read",
    cover: "/blog/aod-9604-and-the-reality-of-commercial-weight-loss-claims/cover",
    href: "/blog/aod-9604-and-the-reality-of-commercial-weight-loss-claims",
  },
  {
    slug: "selank-immunomodulation-and-gene-expression",
    title: "Selank: Immunomodulation and Gene Expression",
    excerpt: "Selank alters the inflammatory baseline by modulating gene expression, specifically downregulating C3 and Xcr1 mRNA in animal models.",
    category: "Science",
    date: "Jul 20, 2026",
    dateSort: 20260720,
    readTime: "3 min read",
    cover: "/blog/selank-immunomodulation-and-gene-expression/cover",
    href: "/blog/selank-immunomodulation-and-gene-expression",
  },
  {
    slug: "oral-vs-injectable-glp-1s-orforglipron-pharmacokinetics",
    title: "Oral vs. Injectable GLP-1s: Orforglipron Pharmacokinetics",
    excerpt: "Orforglipron is a daily oral nonpeptide GLP-1 receptor agonist. Evaluate your starting metabolic deficit to decide between oral and injectable dual agonists.",
    category: "Science",
    date: "Jul 19, 2026",
    dateSort: 20260719,
    readTime: "2 min read",
    cover: "/blog/oral-vs-injectable-glp-1s-orforglipron-pharmacokinetics/cover",
    href: "/blog/oral-vs-injectable-glp-1s-orforglipron-pharmacokinetics",
  },
  {
    slug: "tissue-recovery-bpc-157-vs-tb-500-mechanisms",
    title: "Tissue Recovery: BPC-157 vs TB-500 Mechanisms",
    excerpt: "Understanding tissue recovery mechanisms requires mapping molecular repair pathways against objective biomarker data to track distinct physiological changes.",
    category: "Science",
    date: "Jul 18, 2026",
    dateSort: 20260718,
    readTime: "3 min read",
    cover: "/blog/tissue-recovery-bpc-157-vs-tb-500-mechanisms/cover",
    href: "/blog/tissue-recovery-bpc-157-vs-tb-500-mechanisms",
  },
  {
    slug: "pharmacological-profiles-pt-141-vs-melanotan-ii",
    title: "Pharmacological Profiles: PT-141 vs. Melanotan II Realities",
    excerpt: "PT-141 and Melanotan II present distinct clinical realities. While bremelanotide holds approval for HSDD, trial data reveals negligible objective improvements.",
    category: "Science",
    date: "Jul 17, 2026",
    dateSort: 20260717,
    readTime: "2 min read",
    cover: "/blog/pharmacological-profiles-pt-141-vs-melanotan-ii/cover",
    href: "/blog/pharmacological-profiles-pt-141-vs-melanotan-ii",
  },
  {
    slug: "pharmacokinetic-profiles-cjc-1295-vs-sermorelin",
    title: "Pharmacokinetic Profiles: CJC-1295 vs. Sermorelin",
    excerpt: "The difference between CJC-1295 and Sermorelin lies in their pharmacokinetic architecture, contrasting a multi-day sustained baseline with a rapid endogenous",
    category: "Science",
    date: "Jul 16, 2026",
    dateSort: 20260716,
    readTime: "3 min read",
    cover: "/blog/pharmacokinetic-profiles-cjc-1295-vs-sermorelin/cover",
    href: "/blog/pharmacokinetic-profiles-cjc-1295-vs-sermorelin",
  },
  {
    slug: "tesamorelin-pharmacokinetics-and-clinical-utility",
    title: "Tesamorelin Pharmacokinetics and Clinical Utility",
    excerpt: "Tesamorelin is an FDA-approved growth hormone-releasing hormone analog. In specific clinical populations, data demonstrates it reduces visceral and hepatic fat.",
    category: "Science",
    date: "Jul 16, 2026",
    dateSort: 20260716,
    readTime: "3 min read",
    cover: "/blog/tesamorelin-pharmacokinetics-and-clinical-utility/cover",
    href: "/blog/tesamorelin-pharmacokinetics-and-clinical-utility",
  },
  {
    slug: "retatrutide-vs-tirzepatide",
    title: "Retatrutide vs Tirzepatide: a practical comparison",
    excerpt:
      "Two GLP-1s, two pharmacokinetic profiles, two very different titration curves. Here's how we'd decide between them, based on what the trials actually show.",
    category: "Protocols",
    date: "May 18, 2026",
    dateSort: 20260518,
    readTime: "8 min read",
    cover: "/blog/retatrutide-vs-tirzepatide/cover",
    href: "/blog/retatrutide-vs-tirzepatide",
  },
  {
    slug: "reading-free-testosterone",
    title: "How to read a free testosterone trend line",
    excerpt:
      "Total T tells you almost nothing. Free T tells you most of the story. This is how to read the shape, not just the number.",
    category: "Biomarkers",
    date: "May 12, 2026",
    dateSort: 20260512,
    readTime: "6 min read",
    cover: "/blog/reading-free-testosterone/cover",
    href: "/blog/reading-free-testosterone",
  },
  {
    slug: "reconstitution-without-anxiety",
    title: "Reconstitution math, without the anxiety",
    excerpt:
      "Most reconstitution errors are not math errors, they're attention errors. A two-step process that removes every chance for either.",
    category: "Protocols",
    date: "May 4, 2026",
    dateSort: 20260504,
    readTime: "5 min read",
    cover: "/blog/reconstitution-without-anxiety/cover",
    href: "/blog/reconstitution-without-anxiety",
  },
];

/**
 * Derived from the posts that actually exist, most-used category first.
 *
 * This used to be a hand-written list that included "Nutrition" and
 * "Recovery", neither of which any post has ever used, so those two chips
 * always filtered the grid down to an empty state. Deriving it means a
 * category chip can never appear without at least one post behind it, and a
 * new category shows up the moment a post declares it.
 */
export const BLOG_CATEGORIES: string[] = [
  "All",
  ...Object.entries(
    BLOG_POSTS.reduce<Record<string, number>>((acc, p) => {
      acc[p.category] = (acc[p.category] ?? 0) + 1;
      return acc;
    }, {})
  )
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([category]) => category),
];
