import { COMPOUNDS, TIER_ORDER, type CompoundRef, type Tier } from "./compounds";

/**
 * Community report database.
 *
 * ⚠️ THE DATA BELOW IS SYNTHETIC. Every report is generated by the seeded
 * function at the bottom of this file so the page has something to render
 * during design. It is NOT real user data and must not ship as though it is.
 *
 * `IS_SAMPLE_DATA` gates it. Flip it to false once `loadReports()` is reading
 * real submissions and every surface that renders a number will drop its
 * "sample data" labelling automatically, the flag is read by the page, not
 * just by this module, so there is exactly one switch to throw.
 */
export const IS_SAMPLE_DATA = true;

// ---------------------------------------------------------------------------
// Vocabularies. Fixed lists, because free-text answers can't be counted and
// an open field on an anonymous form is a moderation problem.
// ---------------------------------------------------------------------------

export const POSITIVE_EFFECTS = [
  "more energy", "better sleep", "fat loss", "appetite suppression",
  "faster recovery", "joint / tendon relief", "skin / hair", "mood / focus",
  "libido", "strength / pump", "cognition", "injury healing",
  "cardiovascular / circulation", "better bloodwork",
] as const;

export const SIDE_EFFECTS = [
  "none / clean", "injection-site irritation", "fatigue", "GI / nausea",
  "headache", "heart rate", "sleep disruption", "mood / anxiety",
  "appetite change",
] as const;

export const TARGETS = [
  "appetite / weight", "blood sugar / metabolic", "energy / endurance",
  "recovery / injury", "joint / tendon comfort", "sleep", "mood / anxiety",
  "focus / cognition", "skin / hair", "libido / sexual function",
  "body composition", "immune / inflammation",
  "cardiovascular / blood pressure", "longevity / healthspan",
] as const;

export const DURATIONS = ["1 wk", "2 wk", "4 wk", "6 wk", "8 wk", "12 wk", "16 wk+"] as const;
export const UNITS = ["mcg", "mg", "iu"] as const;
export const ROUTES = ["sub-q", "oral", "nasal", "topical", "other"] as const;
export const AGE_BANDS = ["21-29", "30-39", "40-49", "50-59", "60+"] as const;

export interface Report {
  id: string;
  slug: string;
  /** 1 no effect · 2 barely · 3 modest · 4 clearly worked · 5 textbook */
  outcome: number;
  positives: string[];
  sides: string[];
  targets: string[];
  duration: string;
  monthIndex: number;
  again: "yes" | "no" | "unsure";
}

// ---------------------------------------------------------------------------
// Confidence bands. A count alone tells a reader nothing, 4 reports and 40
// reports render the same width otherwise. These are the thresholds the page
// labels bars with, and they're deliberately conservative.
// ---------------------------------------------------------------------------

export const BANDS = [
  { min: 100, label: "established", note: "enough reports to be worth weighing" },
  { min: 30, label: "early signal", note: "a pattern, not a conclusion" },
  { min: 10, label: "directional", note: "leaning, but thin" },
  { min: 5, label: "very early", note: "a first read only" },
  { min: 1, label: "gathering", note: "too few to read" },
  { min: 0, label: "no reports", note: "nobody has filed one" },
] as const;

export function bandFor(n: number) {
  return BANDS.find((b) => n >= b.min)!;
}

/** The threshold below which no per-compound breakdown is published. */
export const READ_THRESHOLD = 5;

// ---------------------------------------------------------------------------
// Seeded generator, mulberry32. Deterministic so the server and the client
// render identical markup; Math.random() here would be a hydration mismatch
// and a different page on every build.
// ---------------------------------------------------------------------------

function mulberry32(seed: number) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function pick<T>(rnd: () => number, arr: readonly T[]): T {
  return arr[Math.floor(rnd() * arr.length)];
}

function sample<T>(rnd: () => number, arr: readonly T[], max: number): T[] {
  const n = 1 + Math.floor(rnd() * max);
  const out = new Set<T>();
  let guard = 0;
  while (out.size < n && guard++ < 40) out.add(pick(rnd, arr));
  return [...out];
}

export const MONTHS = ["May 26", "Jun 26", "Jul 26", "Aug 26"];

/**
 * Weights reports toward compounds people actually run, so the distribution
 * has a head and a long tail rather than being uniform, a flat spread across
 * all 58 would make every chart look identical and prove nothing.
 */
const POPULAR = [
  "retatrutide", "mots-c", "tesamorelin", "tirzepatide",
  "cjc-1295-no-dac-ipamorelin-blend", "klow", "hcg", "nad-plus",
  "melanotan-i", "semaglutide", "5-amino-1mq", "glow", "ipamorelin",
  "bpc-157-tb-500-blend", "slu-pp-915", "ss-31", "bpc-157",
];

function buildReports(): Report[] {
  const rnd = mulberry32(20260806);
  const reports: Report[] = [];
  const pool = COMPOUNDS.map((c) => c.slug);

  // 41 of 58 compounds carry at least one report; the rest sit at zero, which
  // the board shows honestly rather than hiding.
  const covered = [
    ...POPULAR,
    ...pool.filter((s) => !POPULAR.includes(s)).slice(0, 24),
  ];

  let id = 0;
  for (const slug of covered) {
    const rank = POPULAR.indexOf(slug);
    const base = rank >= 0 ? Math.max(4, 34 - rank * 2) : 1 + Math.floor(rnd() * 4);
    const count = Math.max(1, Math.round(base * (0.75 + rnd() * 0.5)));

    for (let i = 0; i < count; i++) {
      reports.push({
        id: `r${id++}`,
        slug,
        outcome: 1 + Math.floor(rnd() * 5),
        positives: rnd() > 0.14 ? sample(rnd, POSITIVE_EFFECTS, 3) : [],
        sides: rnd() > 0.14 ? sample(rnd, SIDE_EFFECTS, 2) : [],
        targets: rnd() > 0.64 ? sample(rnd, TARGETS, 2) : [],
        duration: pick(rnd, DURATIONS),
        // Skewed toward RECENT months so the cumulative curve ramps upward.
        // `rnd()*rnd()` is biased low, so it has to be inverted, using it
        // directly piles every report into month 0 and the trend line comes
        // out saturated at the start and flat thereafter.
        monthIndex: MONTHS.length - 1 - Math.floor(rnd() * rnd() * MONTHS.length),
        again: rnd() > 0.24 ? "yes" : rnd() > 0.5 ? "unsure" : "no",
      });
    }
  }
  return reports;
}

export const REPORTS: Report[] = buildReports();

// ---------------------------------------------------------------------------
// Derived aggregates
// ---------------------------------------------------------------------------

export interface CompoundStat extends CompoundRef {
  count: number;
  band: (typeof BANDS)[number];
  topPositive?: string;
  avgOutcome?: number;
}

export function compoundStats(): CompoundStat[] {
  return COMPOUNDS.map((c) => {
    const rs = REPORTS.filter((r) => r.slug === c.slug);
    const count = rs.length;

    let topPositive: string | undefined;
    let avgOutcome: number | undefined;

    // Only publish a breakdown once there are enough reports to bother.
    if (count >= READ_THRESHOLD) {
      const tally = new Map<string, number>();
      for (const r of rs) for (const p of r.positives) tally.set(p, (tally.get(p) ?? 0) + 1);
      topPositive = [...tally.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))[0]?.[0];
      avgOutcome = rs.reduce((s, r) => s + r.outcome, 0) / count;
    }

    return { ...c, count, band: bandFor(count), topPositive, avgOutcome };
  }).sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
}

/** Count how many reports selected each option in a vocabulary. */
export function tally(
  field: "positives" | "sides" | "targets",
  vocab: readonly string[]
): { label: string; count: number }[] {
  const map = new Map<string, number>(vocab.map((v) => [v, 0]));
  for (const r of REPORTS) for (const v of r[field]) map.set(v, (map.get(v) ?? 0) + 1);
  return [...map.entries()]
    .map(([label, count]) => ({ label, count }))
    .sort((a, b) => b.count - a.count);
}

/** How many reports answered a given question at all. */
export function answered(field: "positives" | "sides" | "targets"): number {
  return REPORTS.filter((r) => r[field].length > 0).length;
}

/** Cumulative reports per month bucket. */
export function cumulative(): { month: string; total: number; added: number }[] {
  let running = 0;
  return MONTHS.map((month, i) => {
    const added = REPORTS.filter((r) => r.monthIndex === i).length;
    running += added;
    return { month, total: running, added };
  });
}

export function summary() {
  const stats = compoundStats();
  const withReports = stats.filter((s) => s.count > 0);
  return {
    reports: REPORTS.length,
    compoundsCovered: withReports.length,
    compoundsTotal: COMPOUNDS.length,
    readable: stats.filter((s) => s.count >= READ_THRESHOLD).length,
    gathering: stats.filter((s) => s.count > 0 && s.count < READ_THRESHOLD).length,
    zero: stats.filter((s) => s.count === 0).length,
  };
}

// ---------------------------------------------------------------------------
// Per-compound reads, everything the /community-notes/[slug] page renders.
// The same publishing rule applies as everywhere else: below READ_THRESHOLD
// no breakdown is published, only the count.
// ---------------------------------------------------------------------------

export function reportsFor(slug: string): Report[] {
  return REPORTS.filter((r) => r.slug === slug);
}

/** Outcome labels, index-aligned with the 1–5 scale the form records. */
export const OUTCOME_LABELS = [
  "no effect",
  "barely",
  "modest",
  "clearly worked",
  "textbook",
] as const;

/** Reports per outcome step, 1–5, every step listed even at zero, so the
 *  distribution's shape is honest about where nobody landed. */
export function outcomeDist(slug: string): { label: string; count: number }[] {
  const rs = reportsFor(slug);
  return OUTCOME_LABELS.map((label, i) => ({
    label: `${i + 1} · ${label}`,
    count: rs.filter((r) => r.outcome === i + 1).length,
  }));
}

/** This compound's tally over one vocabulary, zero rows dropped. */
export function tallyFor(
  slug: string,
  field: "positives" | "sides" | "targets",
  vocab: readonly string[]
): { label: string; count: number }[] {
  const rs = reportsFor(slug);
  const map = new Map<string, number>(vocab.map((v) => [v, 0]));
  for (const r of rs) for (const v of r[field]) map.set(v, (map.get(v) ?? 0) + 1);
  return [...map.entries()]
    .map(([label, count]) => ({ label, count }))
    .filter((d) => d.count > 0)
    .sort((a, b) => b.count - a.count);
}

/** Would-run-it-again split for one compound. */
export function againSplit(slug: string): { yes: number; no: number; unsure: number } {
  const rs = reportsFor(slug);
  return {
    yes: rs.filter((r) => r.again === "yes").length,
    no: rs.filter((r) => r.again === "no").length,
    unsure: rs.filter((r) => r.again === "unsure").length,
  };
}

/** Duration spread for one compound, in the form's fixed buckets. */
export function durationDist(slug: string): { label: string; count: number }[] {
  const rs = reportsFor(slug);
  return DURATIONS.map((d) => ({
    label: d,
    count: rs.filter((r) => r.duration === d).length,
  })).filter((d) => d.count > 0);
}

export { TIER_ORDER };
export type { Tier, CompoundRef };
