/**
 * The Library: an independent peptide reference built from the app catalog.
 *
 * Data comes from `data/library-peptides.json`, generated by
 * `scripts/build-library-data.mjs` out of the iOS catalog. Never hand-edit the
 * JSON, re-run the generator.
 *
 * Route shape (one hub + one page per chapter, so each long-tail query gets its
 * own indexable target):
 *
 *   /library
 *   /library/all-peptides
 *   /library/<category>
 *   /library/<category>/<peptide>
 *   /library/<category>/<peptide>/<chapter>
 */
import PEPTIDE_DATA from "./data/library-peptides.json";

/**
 * Dashes to commas, for body prose.
 *
 * Different job from `normalizeDashes`. That one splits a display string into
 * two sentences, which is right for a takeaway but wrong mid-paragraph: the
 * catalog uses PAIRED dashes as parentheses ("gastric stability—surviving
 * extreme pH—distinguishes it"), and splitting those leaves two fragments.
 * A comma reads correctly in both the paired and the single case.
 *
 * En dashes are only converted when spaced. An unspaced one is a numeric range
 * ("250–500 mcg", "2–8°C") and turning that into "250, 500" would change what
 * the page says.
 */
export function dashesToCommas(text: string): string {
  return text
    // Em dash, unless it sits between two digits.
    .replace(/(\d)\s*—\s*(\d)/g, "$1-$2")
    .replace(/\s*—\s*/g, ", ")
    // Spaced en dash only.
    .replace(/\s+–\s+/g, ", ")
    // A dash next to punctuation leaves doubles behind.
    .replace(/,\s*,/g, ",")
    .replace(/\s+,/g, ",")
    .replace(/,\s*([.;:!?])/g, "$1")
    .replace(/\s{2,}/g, " ");
}


export type CategorySlug =
  | "weight-loss"
  | "recovery"
  | "performance"
  | "longevity"
  | "aesthetics"
  | "cognitive";

export type Tier = "S" | "A" | "B" | "C" | "D" | "F";

export interface QuickFact {
  key: string;
  value: string;
}
export interface EvidenceClaim {
  claim: string;
  tier: string;
  note?: string;
}
export interface Trial {
  name: string;
  date?: string;
  journal?: string;
  headlineStat?: string;
}
export interface Source {
  url: string;
  title: string;
  type?: string;
  authors?: string[];
  year?: number;
}
export interface PkPoint {
  label: string;
  value: number;
}
export interface PkChart {
  title: string;
  unit: string;
  halfLifeLabel: string;
  routeLabel?: string;
  points: PkPoint[];
}
export interface ChapterSection {
  subheader: string;
  body: string;
  caption: string | null;
  pkChart: PkChart | null;
}
export interface Chapter {
  key: string;
  title: string;
  sections: ChapterSection[];
}

export interface Peptide {
  slug: string;
  name: string;
  category: CategorySlug;
  sectionLabel: string;
  sectionIcon: string | null;
  topics: string[];
  subtitle: string;
  description: string;
  researchTier: Tier | null;
  isFeatured: boolean;
  standardDose: { low?: number; high?: number; unit?: string; frequency?: string } | null;
  doseCard: { primary?: string; frequency?: string } | null;
  reconstitution: { vialMg?: number; recommendedBacMl?: number; notes?: string } | null;
  halfLife: string | null;
  route: string[];
  commonStacks: string[];
  contraindications: string[];
  quickFacts: QuickFact[];
  evidenceSummary: string[];
  evidenceClaims: EvidenceClaim[];
  researchHeadlines: { lede: string; body: string; tier?: string }[];
  trials: Trial[];
  sources: Source[];
  chapters: Chapter[];
  readMinutes: number;
  publishedAt: string | null;
  updatedAt: string | null;
}

/**
 * The catalog, with dashes normalised once at load.
 *
 * Doing this per component missed every surface that renders a catalog string
 * without going through `Prose`: card subtitles, composed FAQ answers, search
 * blurbs, meta descriptions, JSON-LD, the OG images, and `/llms.txt`. Cleaning
 * the data instead means there is exactly one place to get it right, and no
 * new consumer can reintroduce one.
 *
 * Runs at module load, which on this site is build time — every library route
 * is statically generated.
 */
function cleanPeptide(p: Peptide): Peptide {
  return {
    ...p,
    subtitle: dashesToCommas(p.subtitle),
    description: dashesToCommas(p.description),
    halfLife: p.halfLife ? dashesToCommas(p.halfLife) : p.halfLife,
    contraindications: p.contraindications.map(dashesToCommas),
    reconstitution: p.reconstitution
      ? {
          ...p.reconstitution,
          notes: p.reconstitution.notes ? dashesToCommas(p.reconstitution.notes) : p.reconstitution.notes,
        }
      : p.reconstitution,
    doseCard: p.doseCard
      ? {
          ...p.doseCard,
          primary: p.doseCard.primary ? dashesToCommas(p.doseCard.primary) : p.doseCard.primary,
          frequency: p.doseCard.frequency ? dashesToCommas(p.doseCard.frequency) : p.doseCard.frequency,
        }
      : p.doseCard,
    sources: p.sources.map((src) => ({ ...src, title: dashesToCommas(src.title) })),
    researchHeadlines: p.researchHeadlines.map((h) => ({
      ...h,
      lede: dashesToCommas(h.lede),
      body: dashesToCommas(h.body),
    })),
    evidenceSummary: p.evidenceSummary.map(dashesToCommas),
    evidenceClaims: p.evidenceClaims.map((c) => ({
      ...c,
      note: c.note ? dashesToCommas(c.note) : c.note,
    })),
    quickFacts: p.quickFacts.map((f) => ({ ...f, value: dashesToCommas(f.value) })),
    trials: p.trials.map((t) => ({
      ...t,
      headlineStat: t.headlineStat ? dashesToCommas(t.headlineStat) : t.headlineStat,
    })),
    chapters: p.chapters.map((ch) => ({
      ...ch,
      sections: ch.sections.map((sec) => ({ ...sec, body: dashesToCommas(sec.body) })),
    })),
  };
}

export const PEPTIDES = (PEPTIDE_DATA as unknown as Peptide[]).map(cleanPeptide);

/* ---- Category identity ---------------------------------------------------
   Ported from the app: `LibraryModels.swift` maps a section label to one of
   five brand ramps (`String.asCategoryGradient`) and the catalog carries an SF
   Symbol per section (`sectionIcon`). The web repeats both mappings so a
   compound reads the same on both surfaces. Two categories legitimately share
   the green ramp, exactly as they do in the app — the icon and the label are
   what separate them, colour is never the only signal. */

export type Ramp = "warm" | "cool" | "green" | "brown" | "gold";
/** `String.asCategoryGradient`, keyed by the app's own section labels. */
const RAMP_BY_SECTION: Record<string, Ramp> = {
  "fat loss & metabolism": "warm",
  "recovery & healing": "cool",
  "recovery & wellness": "cool",
  "growth & GH": "green",
  "growth & hormones": "green",
  "growth & performance": "green",
  "longevity & healthspan": "green",
  "longevity & brain": "brown",
  "focus & cognition": "brown",
  "sexual health": "brown",
  "skin & aesthetics": "gold",
};

export type IconKey =
  | "flame"
  | "bandage"
  | "leaf"
  | "dumbbell"
  | "infinity"
  | "sparkles"
  | "brain"
  | "heart";

/** The catalog's SF Symbol names, resolved to this site's icon set. */
const ICON_BY_SYMBOL: Record<string, IconKey> = {
  "flame.fill": "flame",
  "bandage.fill": "bandage",
  "leaf.fill": "leaf",
  "figure.strengthtraining.traditional": "dumbbell",
  infinity: "infinity",
  sparkles: "sparkles",
  "brain.head.profile": "brain",
  "heart.fill": "heart",
};

export function rampFor(p: Peptide): Ramp {
  return RAMP_BY_SECTION[p.sectionLabel] ?? "warm";
}

/** The compound's own mark, falling back to its category's. */
export function iconFor(p: Peptide): IconKey {
  const mapped = p.sectionIcon ? ICON_BY_SYMBOL[p.sectionIcon] : undefined;
  return mapped ?? categoryBySlug(p.category)?.icon ?? "flame";
}

/* ---- Categories --------------------------------------------------------- */

export interface CategoryMeta {
  slug: CategorySlug;
  label: string;
  /** Used as the page H1 subtitle and the meta description stem. */
  blurb: string;
  /** Brand ramp key, see `--cat-*` in globals.css. Mirrors the app's
      `String.asCategoryGradient`, so a compound wears the same colour here as
      it does in the iOS Library tab. */
  ramp: Ramp;
  /** Icon key, see `CategoryIcon`. Mirrors the app's `sectionIcon`. */
  icon: IconKey;
  /** Opening paragraph on the category page. A category page that is nothing
      but a card grid is a thin page; this is the content that earns it. */
  intro: string;
}

export const CATEGORIES: CategoryMeta[] = [
  {
    slug: "weight-loss",
    icon: "flame",
    label: "Weight Loss",
    ramp: "warm",
    blurb:
      "GLP-1 and metabolic compounds, graded on the trial evidence behind the weight they actually move.",
    intro:
      "Weight-loss peptides are the one corner of this field with large, randomised, placebo-controlled human trials behind it. Semaglutide, tirzepatide, and retatrutide all have published phase 3 data with hard body-weight endpoints, which is why they carry the highest grades in this library. Everything else in the category is graded against that bar. Each entry below lists the dose ranges used in the published protocols, the half-life that sets the injection schedule, and links to the trials themselves.",
  },
  {
    slug: "recovery",
    icon: "bandage",
    label: "Recovery",
    ramp: "cool",
    blurb:
      "Tissue repair, tendon and gut healing compounds, and how much of the evidence is still preclinical.",
    intro:
      "Recovery is the category where the gap between reputation and evidence is widest. BPC-157 and TB-500 are among the most discussed compounds anywhere, and both rest almost entirely on rodent and in-vitro work: no completed randomised human trial exists for either. That is not an argument that they do nothing, it is a statement about what has been measured. The grades below reflect study design, not popularity, so a compound with a strong mechanism and no human data grades low here.",
  },
  {
    slug: "performance",
    icon: "dumbbell",
    label: "Performance",
    ramp: "green",
    blurb:
      "Growth hormone secretagogues, GHRH analogs, and hormonal compounds, with the IGF-1 data behind them.",
    intro:
      "Performance compounds mostly work upstream: rather than supplying growth hormone, they push the pituitary to release its own. GHRH analogs (sermorelin, tesamorelin, CJC-1295) and ghrelin mimetics (ipamorelin, MK-677) raise IGF-1, and IGF-1 is the biomarker nearly every study in this category reports. A handful hold real approvals, tesamorelin for visceral fat and somatropin for deficiency; most do not. Read the grade beside each name before the claim.",
  },
  {
    slug: "longevity",
    icon: "infinity",
    label: "Longevity",
    ramp: "green",
    blurb:
      "Healthspan, mitochondrial, and immune compounds, separated by whether the data is human or rodent.",
    intro:
      "Longevity is the hardest category to evidence, because the endpoint takes decades to measure. What studies actually report are surrogates: NAD+ levels, mitochondrial function, telomerase activity, immune markers. Some compounds here have genuine clinical footing, elamipretide reached late-stage trials and thymosin alpha-1 is approved in dozens of countries. Others rest on mouse lifespan curves. The grades below tell you which is which.",
  },
  {
    slug: "aesthetics",
    icon: "sparkles",
    label: "Aesthetics",
    ramp: "gold",
    blurb: "Skin, collagen, hair, and pigmentation compounds, and what the dermatology literature shows.",
    intro:
      "Aesthetic peptides have an advantage over the rest of the library: skin is easy to biopsy and easy to photograph, so the endpoints are measurable and the studies are shorter. GHK-Cu has decades of dermatology literature on collagen synthesis and wound repair. The melanocortin compounds are a different story, one is an approved drug for a rare photosensitivity disorder, the other is an unapproved analog with real safety signals. The distinction matters and the grades reflect it.",
  },
  {
    slug: "cognitive",
    icon: "brain",
    label: "Cognitive",
    ramp: "brown",
    blurb: "Nootropic and neuroprotective peptides, and the size of the human evidence base.",
    intro:
      "Most cognitive peptides trace back to Russian clinical research from the 1990s and 2000s, which is real published work but rarely replicated to Western regulatory standards. Semax and Selank both have human data behind them; the mechanisms proposed, BDNF upregulation and GABAergic modulation, are plausible and partly demonstrated. Dihexa sits at the other end, with headline rodent results and a retraction in its history. The grades below weigh replication, not novelty.",
  },
];

const CATEGORY_BY_SLUG = new Map(CATEGORIES.map((c) => [c.slug, c]));

export function categoryBySlug(slug: string): CategoryMeta | undefined {
  return CATEGORY_BY_SLUG.get(slug as CategorySlug);
}

/* ---- Chapters -----------------------------------------------------------
   URL slugs deliberately differ from the app's internal chapter keys: the app
   says "dosing" and "paired-stacks", search says "dosage" and "stacking". The
   URL follows search. */

export interface ChapterMeta {
  /** URL segment. */
  slug: string;
  /** Key as it appears in the catalog. */
  key: string;
  label: string;
  /** "<Name> <suffix>" builds the page title. */
  titleSuffix: string;
  descriptionStem: string;
}

export const CHAPTERS: ChapterMeta[] = [
  {
    slug: "how-it-works",
    key: "how-it-works",
    label: "How It Works",
    titleSuffix: "Mechanism of Action",
    descriptionStem: "How {name} works: receptor targets, signalling pathways, and molecular profile.",
  },
  {
    slug: "dosage",
    key: "dosing",
    label: "Dosage",
    titleSuffix: "Dosage and Protocols",
    descriptionStem:
      "{name} dosage protocols reported in published research, plus reconstitution and storage.",
  },
  {
    slug: "side-effects",
    key: "side-effects",
    label: "Side Effects",
    titleSuffix: "Side Effects and Safety",
    descriptionStem: "Reported {name} side effects, contraindications, and safety signals.",
  },
  {
    slug: "research",
    key: "research",
    label: "Research",
    titleSuffix: "Research Evidence",
    descriptionStem: "The {name} evidence base: trials, journals, and what the data does not yet show.",
  },
  {
    slug: "stacking",
    key: "paired-stacks",
    label: "Stacking",
    titleSuffix: "Stacking and Combinations",
    descriptionStem: "Which compounds {name} is paired with, and the rationale behind each combination.",
  },
  {
    slug: "pharmacokinetics",
    key: "pharmacokinetics",
    label: "Pharmacokinetics",
    titleSuffix: "Pharmacokinetics",
    descriptionStem: "{name} half-life, absorption, routes of administration, and clearance.",
  },
];

const CHAPTER_BY_SLUG = new Map(CHAPTERS.map((c) => [c.slug, c]));

export function chapterBySlug(slug: string): ChapterMeta | undefined {
  return CHAPTER_BY_SLUG.get(slug);
}

/* ---- Lookups ------------------------------------------------------------ */

const BY_SLUG = new Map(PEPTIDES.map((p) => [p.slug, p]));

export function peptideBySlug(slug: string): Peptide | undefined {
  return BY_SLUG.get(slug);
}

export function peptidesInCategory(slug: CategorySlug): Peptide[] {
  return PEPTIDES.filter((p) => p.category === slug).sort(byPromise);
}

/** Featured first, then stronger evidence, then alphabetical. */
const TIER_RANK: Record<string, number> = { S: 0, A: 1, B: 2, C: 3, D: 4, F: 5 };
function byPromise(a: Peptide, b: Peptide): number {
  if (a.isFeatured !== b.isFeatured) return a.isFeatured ? -1 : 1;
  const ta = TIER_RANK[a.researchTier ?? "F"] ?? 9;
  const tb = TIER_RANK[b.researchTier ?? "F"] ?? 9;
  if (ta !== tb) return ta - tb;
  return a.name.localeCompare(b.name);
}

export const ALL_PEPTIDES_SORTED = [...PEPTIDES].sort(byPromise);

/** Homepage "Notable Peptides" deck. */
export function notablePeptides(limit = 24): Peptide[] {
  return ALL_PEPTIDES_SORTED.slice(0, limit);
}

export function chapterFor(p: Peptide, meta: ChapterMeta): Chapter | undefined {
  return p.chapters.find((c) => c.key === meta.key);
}

export function hrefFor(p: Peptide): string {
  return `/library/${p.category}/${p.slug}`;
}

export function chapterHref(p: Peptide, meta: ChapterMeta): string {
  return `${hrefFor(p)}/${meta.slug}`;
}

/** Compounds that name each other in `commonStacks`, resolved and deduped. */
export function relatedPeptides(p: Peptide, limit = 4): Peptide[] {
  const out: Peptide[] = [];
  const seen = new Set([p.slug]);
  for (const slug of p.commonStacks) {
    const hit = BY_SLUG.get(slug);
    if (hit && !seen.has(hit.slug)) {
      seen.add(hit.slug);
      out.push(hit);
    }
  }
  for (const other of peptidesInCategory(p.category)) {
    if (out.length >= limit) break;
    if (!seen.has(other.slug)) {
      seen.add(other.slug);
      out.push(other);
    }
  }
  return out.slice(0, limit);
}

/* ---- Header meta -------------------------------------------------------
   Ported verbatim from the app's `LibraryPeptide` extension in
   `LibraryModels.swift`, so the reference page's spec line and status chip
   read the same as the iOS breakdown header. Thin readers over `quickFacts`,
   deliberately not a second copy of the Quick Facts grid. */

/** First quick fact whose key contains `key`, case-insensitive. */
export function quickFact(p: Peptide, key: string): string | null {
  const hit = p.quickFacts.find((f) => f.key.toLowerCase().includes(key.toLowerCase()));
  const v = hit?.value?.trim();
  return v ? v : null;
}

/** "Prescription-only, FDA-approved" etc. Null for research compounds. */
export function legalStatus(p: Peptide): string | null {
  return quickFact(p, "Legal Status");
}

/** "Mounjaro, Zepbound" — commercial names, when the catalog has them.
    Some entries put a whole sentence in this field ("sold as FDA-approved for
    Barth syndrome (Sept 2025) — general research-vendor form has no
    trademarked brand"), which is true but is not a brand list and blows the
    spec line onto three lines. Anything that is not a short comma-separated
    list is dropped; the full text still shows in Quick Facts. */
export function brandNames(p: Peptide): string | null {
  let v = quickFact(p, "Brand Names");
  if (!v) return null;
  // Trailing gloss ("Scenesse (FDA-approved implant for EPP)") belongs in
  // Quick Facts, not in a one-line spec.
  v = v.replace(/\s*\([^)]*\)/g, "").trim().replace(/,$/, "");
  if (!v || v.length > 44) return null;
  if (/[.;:—]|\bno\b|\bnone\b|\bn\/a\b/i.test(v)) return null;
  return v;
}

/**
 * Regulatory standing, read off the catalog's legal-status text.
 *
 * A plain substring test for "approved" is wrong here and dangerously so: 17
 * of the 32 compounds carrying a legal status open with "Not FDA-approved",
 * and a card that prints "FDA-approved" beside an investigational compound is
 * a false regulatory claim on a health page. So the test looks at the FIRST
 * approval word in the string and checks the run of text immediately before it
 * for a negation, which is where the catalog always puts one.
 */
export type Regulatory = "approved" | "approved-narrow" | "otc" | "research";

const NEGATION = /\b(not|no|never|without|un)\b/;

export function regulatory(p: Peptide): Regulatory {
  const raw = legalStatus(p);
  if (!raw) {
    // No status fact. The S tier is defined as regulatory approval, so it can
    // stand in; anything else stays unclaimed.
    return p.researchTier === "S" ? "approved" : "research";
  }
  const s = raw.toLowerCase();
  const at = s.search(/approv/);
  if (at < 0) {
    return s.includes("dietary supplement") || s.includes("cosmetic") ? "otc" : "research";
  }
  // 40 characters is enough to catch "not currently sold as an FDA-approved"
  // without reaching back into a previous clause.
  if (NEGATION.test(s.slice(Math.max(0, at - 40), at))) {
    return s.includes("dietary supplement") ? "otc" : "research";
  }
  // Approved, but the catalog qualifies it to one indication ("FDA-approved
  // for Barth syndrome specifically"). Saying that plainly is the difference
  // between a reference and a marketing page.
  return /\bspecifically\b|\bfor specific indications\b|\bfor [a-z/ -]+ (syndrome|protoporphyria|induction)/.test(s)
    ? "approved-narrow"
    : "approved";
}

/** True only for an unqualified or indication-limited FDA approval. */
export function isRegulatoryApproved(p: Peptide): boolean {
  const r = regulatory(p);
  return r === "approved" || r === "approved-narrow";
}

/** Status chip label, or null. An ungraded compound with no legal-status fact
    makes no claim either way, so it stays silent rather than mislabel. */
export function regulatoryStatusLabel(p: Peptide): string | null {
  switch (regulatory(p)) {
    case "approved":
      return "FDA-Approved";
    case "approved-narrow":
      return "FDA-Approved for one indication";
    case "otc":
      return "Sold as a supplement";
    default:
      return p.researchTier === null && !legalStatus(p) ? null : "Research Compound";
  }
}

/** "Approximately 5 days (120 hours)" → "~5 days".
    The catalog also carries clause-strung values ("Under 30 minutes in animal
    PK; cleared from plasma within ~4 hours"), which are correct but far too
    long for a spec line, so the first clause wins and anything still over-long
    is dropped rather than truncated mid-fact. */
export function halfLifeShort(p: Peptide): string | null {
  let s = quickFact(p, "Half-Life") ?? p.halfLife;
  if (!s) return null;
  const semi = s.indexOf(";");
  if (semi > 0) s = s.slice(0, semi);
  const paren = s.indexOf("(");
  if (paren > 0) s = s.slice(0, paren);
  s = s.replace(/approximately/gi, "~").replace(/approx\./gi, "~").replace(/\s+/g, " ").trim();
  s = s.replace(/[.,]$/, "");
  if (!s || s.length > 34) return null;
  // A half-life is a quantity. Some entries hedge in prose instead ("Short
  // plasma half-life", "Expected on the order of minutes"), and prefixing that
  // with "~" produces a spec line that states nothing. No digit, no figure.
  if (!/\d/.test(s)) return null;
  return /^[~<>]/.test(s) ? s : `~${s}`;
}

/** The spec line under the title: "GLP-1 / GIP DUAL AGONIST · T1/2 ~5 DAYS". */
export function specLine(p: Peptide): string | null {
  const parts: string[] = [];
  // A classification is a short noun phrase. A few entries run a full clause
  // through this field, and an all-caps eyebrow is the worst place to wrap.
  const cls = quickFact(p, "Class");
  if (cls && cls.length <= 52 && !/[.;]/.test(cls)) parts.push(cls);
  return parts.length ? parts.join(" · ") : null;
}

/** The compound's plasma-concentration curve, wherever it sits in the
    chapters. 29 of 54 compounds carry one; the rest render the half-life
    facts alone rather than a fabricated curve. */
export function pkChartFor(p: Peptide): PkChart | null {
  for (const ch of p.chapters) {
    for (const sec of ch.sections) {
      if (sec.pkChart?.points?.length) return sec.pkChart;
    }
  }
  return null;
}

/* ---- Display copy -------------------------------------------------------
   The catalog is written for the app, where an em dash reads fine inside a
   compact card. On the web it is against house style (see AGENTS.md) and, set
   in a takeaways block, a run of dashed clauses reads as machine output. These
   only touch DISPLAY strings — takeaways and the header lead. Body prose is
   left exactly as written, because rewriting punctuation mid-sentence in a
   paragraph risks changing what it says. */

/** "A — B" becomes "A. B"; "A – B" and stray double hyphens go the same way.
    Splitting a clause off into its own sentence leaves the new sentence
    lowercase, so every sentence start is re-capitalised afterwards. */
export function normalizeDashes(text: string): string {
  const flattened = text
    .replace(/\s*[—–]\s*/g, ". ")
    .replace(/\s+--\s+/g, ". ")
    .replace(/\.\s*\./g, ".")
    .replace(/\s{2,}/g, " ")
    .trim();
  return sentenceCase(flattened);
}

/** Capitalises the first letter of the string and of every sentence in it. */
function sentenceCase(text: string): string {
  return text
    .replace(/^\s*([a-z])/, (_m, c: string) => c.toUpperCase())
    .replace(/([.!?]\s+)([a-z])/g, (_m, sep: string, c: string) => sep + c.toUpperCase());
}

/**
 * Key takeaways, as plain statements.
 *
 * The catalog's `evidenceSummary` mixes real findings with bookkeeping about
 * our own database ("3 tracked outcome areas with graded citations"), which
 * tells a reader nothing about the compound. Those are dropped. What is left
 * is rewritten into flat sentences: no bold, no dashes, no leading label.
 */
export function takeawaysFor(p: Peptide): string[] {
  const out: string[] = [];

  // What it is, built from the subtitle so it can never contradict the header.
  // The leading article is kept and lowercased ("An FDA-approved hormone" ->
  // "is an FDA-approved hormone"); dropping it produced "is FDA-approved
  // hormone".
  const subtitle = normalizeDashes(p.subtitle).replace(/\.$/, "");
  const lead = /^(An?|The)\s/i.test(subtitle)
    ? `${p.name} is ${subtitle.charAt(0).toLowerCase()}${subtitle.slice(1)}.`
    : `${p.name}. ${subtitle}.`;
  out.push(lead);

  for (const line of p.evidenceSummary) {
    // Database bookkeeping, not a finding about the compound.
    if (/tracked outcome area|graded citations|^classified as/i.test(line)) continue;

    let t = normalizeDashes(line);
    // The grade scale is S,A,B,C,D,F — `[A-F]` silently missed every S-tier
    // compound and left the raw "REGEN Research Tier S." label in place.
    t = t.replace(
      /^REGEN Research Tier ([SA-F])\b\.?\s*/i,
      (_m, tier: string) => `The research grade is ${tier.toUpperCase()}. `
    );
    t = t.replace(/^Strongest documented use case:\s*/i, "The best documented use is ");
    t = sentenceCase(t.trim());
    if (!/[.!?]$/.test(t)) t += ".";
    if (t.length > 2) out.push(t);
  }

  return out.slice(0, 4);
}

/* ---- Section shape ------------------------------------------------------
   The app's breakdown does not render every section as prose: summary,
   safety, and procedural blocks are cards with a labelled header ("Reported
   effects", "When to stop", "Reconstitution & storage"). The catalog's own
   subheaders say which is which, so the same split is reproducible on the web
   without inventing structure the data does not support. */

export type SectionKind = "summary" | "safety" | "protocol" | null;

/** Classify a section from its subheader. Anything unmatched stays prose. */
export function sectionKind(subheader: string): SectionKind {
  const h = subheader.toLowerCase();
  if (/\bat a glance\b|\bkey (findings|points|takeaway)|\bsummary\b/.test(h)) return "summary";
  if (/\bsafety\b|\bwhat to monitor\b|\bside.effect|\bcontraindicat|\bwhen to stop\b|\bavoid\b|\bwarning/.test(h))
    return "safety";
  if (/\breconstitut|\bstorage\b|\bprotocol\b|\bhow to (use|inject)\b|\bpreparation\b/.test(h))
    return "protocol";
  return null;
}

/** The label shown on a callout's header row. */
export function sectionKindLabel(kind: Exclude<SectionKind, null>): string {
  switch (kind) {
    case "summary":
      return "Key points";
    case "safety":
      return "Safety";
    case "protocol":
      return "Protocol";
  }
}

/* ---- Dates --------------------------------------------------------------
   The catalog stores ISO timestamps. Rendering one raw ("2026-08-18T00:00:00
   .000Z") in a byline is a credibility leak on a page whose whole pitch is
   that it is maintained. */
export function formatDate(iso?: string | null): string | null {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(+d)) return null;
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  });
}

/* ---- Alphabetical index -------------------------------------------------
   An A-Z index is the cheapest crawl surface a reference site has: one page
   that links every compound, grouped so a reader can jump. Digits and symbols
   collapse into "#". */
export interface AlphaGroup {
  letter: string;
  items: Peptide[];
}

export function alphaGroups(items: Peptide[] = PEPTIDES): AlphaGroup[] {
  const map = new Map<string, Peptide[]>();
  for (const p of [...items].sort((a, b) => a.name.localeCompare(b.name))) {
    const first = p.name[0]?.toUpperCase() ?? "#";
    const letter = /[A-Z]/.test(first) ? first : "#";
    const bucket = map.get(letter);
    if (bucket) bucket.push(p);
    else map.set(letter, [p]);
  }
  return [...map.entries()]
    .map(([letter, items]) => ({ letter, items }))
    .sort((a, b) => (a.letter === "#" ? 1 : b.letter === "#" ? -1 : a.letter.localeCompare(b.letter)));
}

/** Tier counts for a set of compounds, strongest first. Powers the evidence
    breakdown strip on the category pages. */
export function tierSpread(items: Peptide[]): { tier: Tier; count: number }[] {
  const order: Tier[] = ["S", "A", "B", "C", "D", "F"];
  return order
    .map((tier) => ({ tier, count: items.filter((p) => p.researchTier === tier).length }))
    .filter((r) => r.count > 0);
}

/** Search index for the hub's client-side filter. Kept tiny on purpose. */
export interface SearchRow {
  slug: string;
  name: string;
  href: string;
  category: string;
  kind: "Peptide" | "Guide";
  blurb: string;
}

export function peptideSearchRows(): SearchRow[] {
  return ALL_PEPTIDES_SORTED.map((p) => ({
    slug: p.slug,
    name: p.name,
    href: hrefFor(p),
    category: categoryBySlug(p.category)?.label ?? p.category,
    kind: "Peptide" as const,
    blurb: p.subtitle,
  }));
}

/**
 * Robots directives for every library page.
 *
 * The defaults leave snippet and image previews at Google's discretion, which
 * truncates the answer-style excerpts a reference page lives on. Unbounded
 * snippets and large image previews are what let these pages surface as rich
 * results and get quoted by AI search.
 */
export const LIBRARY_ROBOTS = {
  index: true,
  follow: true,
  googleBot: {
    index: true,
    follow: true,
    "max-snippet": -1,
    "max-image-preview": "large",
    "max-video-preview": -1,
  },
} as const;
