/**
 * The Library: an independent peptide reference built from the app catalog.
 *
 * Data comes from `data/library-peptides.json`, generated by
 * `scripts/build-library-data.mjs` out of the iOS catalog. Never hand-edit the
 * JSON, re-run the generator.
 *
 * Route shape (one hub + one page per chapter, so each long-tail query gets its
 * own indexable target):
 *
 *   /library
 *   /library/all-peptides
 *   /library/<category>
 *   /library/<category>/<peptide>
 *   /library/<category>/<peptide>/<chapter>
 */
import PEPTIDE_DATA from "./data/library-peptides.json";

export type CategorySlug =
  | "weight-loss"
  | "recovery"
  | "performance"
  | "longevity"
  | "aesthetics"
  | "cognitive";

export type Tier = "S" | "A" | "B" | "C" | "D" | "F";

export interface QuickFact {
  key: string;
  value: string;
}
export interface EvidenceClaim {
  claim: string;
  tier: string;
  note?: string;
}
export interface Trial {
  name: string;
  date?: string;
  journal?: string;
  headlineStat?: string;
}
export interface Source {
  url: string;
  title: string;
  type?: string;
  authors?: string[];
  year?: number;
}
export interface ChapterSection {
  subheader: string;
  body: string;
  caption: string | null;
}
export interface Chapter {
  key: string;
  title: string;
  sections: ChapterSection[];
}

export interface Peptide {
  slug: string;
  name: string;
  category: CategorySlug;
  sectionLabel: string;
  topics: string[];
  subtitle: string;
  description: string;
  researchTier: Tier | null;
  isFeatured: boolean;
  standardDose: { low?: number; high?: number; unit?: string; frequency?: string } | null;
  doseCard: { primary?: string; frequency?: string } | null;
  reconstitution: { vialMg?: number; recommendedBacMl?: number; notes?: string } | null;
  halfLife: string | null;
  route: string[];
  commonStacks: string[];
  contraindications: string[];
  quickFacts: QuickFact[];
  evidenceSummary: string[];
  evidenceClaims: EvidenceClaim[];
  researchHeadlines: { lede: string; body: string; tier?: string }[];
  trials: Trial[];
  sources: Source[];
  chapters: Chapter[];
  readMinutes: number;
  publishedAt: string | null;
  updatedAt: string | null;
}

export const PEPTIDES = PEPTIDE_DATA as unknown as Peptide[];

/* ---- Categories --------------------------------------------------------- */

export interface CategoryMeta {
  slug: CategorySlug;
  label: string;
  /** Used as the page H1 subtitle and the meta description stem. */
  blurb: string;
}

export const CATEGORIES: CategoryMeta[] = [
  {
    slug: "weight-loss",
    label: "Weight Loss",
    blurb:
      "GLP-1 and metabolic compounds, graded on the trial evidence behind the weight they actually move.",
  },
  {
    slug: "recovery",
    label: "Recovery",
    blurb:
      "Tissue repair, tendon and gut healing compounds, and how much of the evidence is still preclinical.",
  },
  {
    slug: "performance",
    label: "Performance",
    blurb:
      "Growth hormone secretagogues, GHRH analogs, and hormonal compounds, with the IGF-1 data behind them.",
  },
  {
    slug: "longevity",
    label: "Longevity",
    blurb:
      "Healthspan, mitochondrial, and immune compounds, separated by whether the data is human or rodent.",
  },
  {
    slug: "aesthetics",
    label: "Aesthetics",
    blurb: "Skin, collagen, hair, and pigmentation compounds, and what the dermatology literature shows.",
  },
  {
    slug: "cognitive",
    label: "Cognitive",
    blurb: "Nootropic and neuroprotective peptides, and the size of the human evidence base.",
  },
];

const CATEGORY_BY_SLUG = new Map(CATEGORIES.map((c) => [c.slug, c]));

export function categoryBySlug(slug: string): CategoryMeta | undefined {
  return CATEGORY_BY_SLUG.get(slug as CategorySlug);
}

/* ---- Chapters -----------------------------------------------------------
   URL slugs deliberately differ from the app's internal chapter keys: the app
   says "dosing" and "paired-stacks", search says "dosage" and "stacking". The
   URL follows search. */

export interface ChapterMeta {
  /** URL segment. */
  slug: string;
  /** Key as it appears in the catalog. */
  key: string;
  label: string;
  /** "<Name> <suffix>" builds the page title. */
  titleSuffix: string;
  descriptionStem: string;
}

export const CHAPTERS: ChapterMeta[] = [
  {
    slug: "how-it-works",
    key: "how-it-works",
    label: "How It Works",
    titleSuffix: "Mechanism of Action",
    descriptionStem: "How {name} works: receptor targets, signalling pathways, and molecular profile.",
  },
  {
    slug: "dosage",
    key: "dosing",
    label: "Dosage",
    titleSuffix: "Dosage and Protocols",
    descriptionStem:
      "{name} dosage protocols reported in published research, plus reconstitution and storage.",
  },
  {
    slug: "side-effects",
    key: "side-effects",
    label: "Side Effects",
    titleSuffix: "Side Effects and Safety",
    descriptionStem: "Reported {name} side effects, contraindications, and safety signals.",
  },
  {
    slug: "research",
    key: "research",
    label: "Research",
    titleSuffix: "Research Evidence",
    descriptionStem: "The {name} evidence base: trials, journals, and what the data does not yet show.",
  },
  {
    slug: "stacking",
    key: "paired-stacks",
    label: "Stacking",
    titleSuffix: "Stacking and Combinations",
    descriptionStem: "Which compounds {name} is paired with, and the rationale behind each combination.",
  },
  {
    slug: "pharmacokinetics",
    key: "pharmacokinetics",
    label: "Pharmacokinetics",
    titleSuffix: "Pharmacokinetics",
    descriptionStem: "{name} half-life, absorption, routes of administration, and clearance.",
  },
];

const CHAPTER_BY_SLUG = new Map(CHAPTERS.map((c) => [c.slug, c]));

export function chapterBySlug(slug: string): ChapterMeta | undefined {
  return CHAPTER_BY_SLUG.get(slug);
}

/* ---- Lookups ------------------------------------------------------------ */

const BY_SLUG = new Map(PEPTIDES.map((p) => [p.slug, p]));

export function peptideBySlug(slug: string): Peptide | undefined {
  return BY_SLUG.get(slug);
}

export function peptidesInCategory(slug: CategorySlug): Peptide[] {
  return PEPTIDES.filter((p) => p.category === slug).sort(byPromise);
}

/** Featured first, then stronger evidence, then alphabetical. */
const TIER_RANK: Record<string, number> = { S: 0, A: 1, B: 2, C: 3, D: 4, F: 5 };
function byPromise(a: Peptide, b: Peptide): number {
  if (a.isFeatured !== b.isFeatured) return a.isFeatured ? -1 : 1;
  const ta = TIER_RANK[a.researchTier ?? "F"] ?? 9;
  const tb = TIER_RANK[b.researchTier ?? "F"] ?? 9;
  if (ta !== tb) return ta - tb;
  return a.name.localeCompare(b.name);
}

export const ALL_PEPTIDES_SORTED = [...PEPTIDES].sort(byPromise);

/** Homepage "Notable Peptides" deck. */
export function notablePeptides(limit = 24): Peptide[] {
  return ALL_PEPTIDES_SORTED.slice(0, limit);
}

export function chapterFor(p: Peptide, meta: ChapterMeta): Chapter | undefined {
  return p.chapters.find((c) => c.key === meta.key);
}

export function hrefFor(p: Peptide): string {
  return `/library/${p.category}/${p.slug}`;
}

export function chapterHref(p: Peptide, meta: ChapterMeta): string {
  return `${hrefFor(p)}/${meta.slug}`;
}

/** Compounds that name each other in `commonStacks`, resolved and deduped. */
export function relatedPeptides(p: Peptide, limit = 4): Peptide[] {
  const out: Peptide[] = [];
  const seen = new Set([p.slug]);
  for (const slug of p.commonStacks) {
    const hit = BY_SLUG.get(slug);
    if (hit && !seen.has(hit.slug)) {
      seen.add(hit.slug);
      out.push(hit);
    }
  }
  for (const other of peptidesInCategory(p.category)) {
    if (out.length >= limit) break;
    if (!seen.has(other.slug)) {
      seen.add(other.slug);
      out.push(other);
    }
  }
  return out.slice(0, limit);
}

/** Search index for the hub's client-side filter. Kept tiny on purpose. */
export interface SearchRow {
  slug: string;
  name: string;
  href: string;
  category: string;
  kind: "Peptide" | "Guide";
  blurb: string;
}

export function peptideSearchRows(): SearchRow[] {
  return ALL_PEPTIDES_SORTED.map((p) => ({
    slug: p.slug,
    name: p.name,
    href: hrefFor(p),
    category: categoryBySlug(p.category)?.label ?? p.category,
    kind: "Peptide" as const,
    blurb: p.subtitle,
  }));
}

/**
 * Robots directives for every library page.
 *
 * The defaults leave snippet and image previews at Google's discretion, which
 * truncates the answer-style excerpts a reference page lives on. Unbounded
 * snippets and large image previews are what let these pages surface as rich
 * results and get quoted by AI search.
 */
export const LIBRARY_ROBOTS = {
  index: true,
  follow: true,
  googleBot: {
    index: true,
    follow: true,
    "max-snippet": -1,
    "max-image-preview": "large",
    "max-video-preview": -1,
  },
} as const;
